version: '3'

services:

  nginx:
    image: 192.168.2.102:5000/image-gen-cdn-openresty:0.2
    container_name: cdn
    volumes:
      - /tmp/openresty/images:/fsimages
    ports:
      - "80:80"

  frontend:
    image: 192.168.2.102:5000/image-gen-frontend:0.3
    container_name: frontend
    environment:
      - IMAGE_GEN_API_URL=imagegen.wreiner.at
