---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql01
  namespace: image-gen
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: ocs-storagecluster-ceph-rbd
