---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rabbit01-mgmt
  namespace: image-gen
spec:
  host: rabbit01-mgmt.wreiner.at
  to:
    kind: Service
    name: rabbit01
  port:
    targetPort: 15672
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
