---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: classification-service-model-pvc
  namespace: image-gen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ocs-storagecluster-ceph-rbd
