---
apiVersion: v1
kind: Service
metadata:
  name: classification-service
  namespace: image-gen
spec:
  selector:
    app: classification-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
